### ISSUE TITLE
Lua Error when you unequipt Heart of Azeroth

### ISSUE THREAD

**Issue by Stanzilla** [SavedInstances/SavedInstances#257]
Just dumping this here before I forget 

8x SavedInstances\SavedInstances-@project-version@.lua:1650: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
[C]: in function `GetAzeriteItemXPInfo'
SavedInstances\SavedInstances-@project-version@.lua:1650: in function `UpdateToonData'
SavedInstances\SavedInstances-@project-version@.lua:3152: in function `Refresh'
SavedInstances\SavedInstances-@project-version@.lua:2585: in function <SavedInstances\SavedInstances.lua:2585>
[C]: ?
Ace3\AceBucket-3.0\AceBucket-3.0-4.lua:73: in function <Ace3\AceBucket-3.0\AceBucket-3.0.lua:71>
Ace3\AceBucket-3.0\AceBucket-3.0-4.lua:89: in function `func'
Ace3\AceTimer-3.0\AceTimer-3.0-17.lua:57: in function <Ace3\AceTimer-3.0\AceTimer-3.0.lua:50>

**Comment by LiangYuxuan** [comment]
I tried unequip and equip, and reloading ui when unequipped, but I still can't reproduce this

**Comment by Stanzilla** [comment]
Hah, you have to put it into your bank

**Comment by LiangYuxuan** [comment]
Still can't reproduce for me :(

Steps here
1. I put the Heart of Azeroth into bank, and open SI's tooltip, no Lua error.
2. Then I reloaded ui, and open SI's tooltip, no Lua error.
3. I exited the game completely , login and open SI's tooltip, no Lua error.
4. I notice my ElvUI databar is still working, then I disable all other addons, reloaded ui or exited the game, then open SI's tooltip, still no Lua error.

Quite weird, but I guess it's blizzard's issue and it was fixed, since it's possible to get info when HoA is in bank. ElvUI got [issue like this](https://git.tukui.org/elvui/elvui/issues/886) on Nov 30, 2018, and it just gone.

**Comment by jdavis57** [comment]
I'm getting a similar error on 1708. In my case, my druid is 111 (never set foot in BFA, hit 111 through dungeons/timewalking/etc). The only way to prevent this error from constantly being displayed (whenever I try to view SavedInstances) was to comment out the code:

```  
if azeriteItemLocation then
    -- local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation)
    -- local currentLevel = C_AzeriteItem.GetPowerLevel(azeriteItemLocation)
    -- t.Artifact = format("%d (%d%%)", currentLevel, xp / totalLevelXP  * 100)
  end
```

Error that is constantly being thrown:

> Message: Interface\AddOns\SavedInstances\SavedInstances-8.1.4.lua:1708: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
Time: Sat Jun 15 22:10:07 2019
Count: 3
Stack: Interface\AddOns\SavedInstances\SavedInstances-8.1.4.lua:1708: bad argument #1 to 'GetAzeriteItemXPInfo' (Usage: local xp, totalLevelXP = C_AzeriteItem.GetAzeriteItemXPInfo(azeriteItemLocation))
Locals: <none>
