### ISSUE TITLE
M+ keys export function across alts

### ISSUE THREAD

**Issue by dpyy** [SavedInstances/SavedInstances#385]
I'm a happy user of SavedInstance for 2 years now, thanks so much for your work. 
 
However, I'm working on an ability to tell my friends what m+ keys I have. Your UI does a great job of showing all my keys between alts but I want an ability to export that. Similar to how simc/WA would do it. A string I can export and paste on a website or another service where I can tell publish the keys that I have. 
 
Every week, me and my friends run into the same situation. Each of us have 4-8 keys each. And every week we play the game of "who has what at what level" game and it's a complete nightmare. 
 
Is this something possible? And if so, any chance we can make it happen? As far as I know there isn't another addon that does this.

**Comment by prg** [comment]
I'm in a similar situation and use [MythicKeystoneTracker](https://github.com/mehness/MythicKeystoneTracker) for that specific problem. It can post all your keys (with links) and character names into guild chat, party chat, etc which basically is a good enough solution for me. I guess being able to export a string to post into messengers or other chats would be a nice feature for some people, too.

MKT has its own share of problems, some of which are probably to blame on the Blizzard API. But I don't think it's being actively worked on anymore, so I would be in favor of dropping it if SavedInstances could provide that functionality.

I have some free time on my hands right now (when I'm not doing keys or taking care of my herd of alts), so I could give this a whirl and open a pull request. I guess the basic functionality should be pretty easy, once I figure out where I can find the documentation for the Blizzard API and the additional libs like all that Ace stuff.

What I'm not quite sure about where this would go UI-wise. Like, place a button somewhere on the tooltip/popup? Add some sort of menu to the minimap button?

Suggestions and hints welcome.

**Comment by garyhighlinebeta** [comment]
That's great news! I think the easiest UI might just be a button next to mythic keystone (one of the rows header in the left) and maybe it can open up a menu to ask for 

- Announce to guild
- announce to party 
- copy string (where you can come up with a simple text format for outside programs)

**Comment by dpyy** [comment]
That's great news! I think the easiest UI might just be a button next to mythic keystone (one of the rows header in the left) and maybe it can open up a menu to ask for

Announce to guild
announce to party
copy string (where you can come up with a simple text format for outside programs)

**Comment by prg** [comment]
So I just did a quick & dirty PoC, which can be found [here](https://github.com/prg/SavedInstances/commit/682be0c0dd281b3b5524eaf3de63243c2f33d8e5).

First of all, after looking at the code I found out that you already can click on each character's key and it will insert a link into the chat input window. Not exactly what we want and quite cumbersome for many characters, but maybe a workaround until this gets fully implemented.

Right now it just dumps all your characters and their keys into `/say`, looking like this:
![Anmerkung 2020-06-23 200326](https://user-images.githubusercontent.com/101409/85439859-c0ed1300-b58d-11ea-8945-0086d4b93aac.png)

You can trigger this by clicking on the cell in the first column, where the label says "Mythic Keystone". I think that's not the worst place to put this functionality, especially when the subsequent cells on that row have a similar on click functionality.

However, I'm not quite sure where to put the "target selection" part of this. In case you rarely switch this, I guess hiding it somewhere in configuration should be fine. On the other hand, if you basically want to change this on the fly it can be a drag to always go through configuration and hunt down that specific option.

Any of the authors/maintainers have an opinion on this?

**Comment by dpyy** [comment]
This is amazing, I will try this tonight. 

I am aware that you can click on each key but it takes a long time when you have 7-8 alts. 

Also, can you add an export function to text? The format can literally be as simple as 
[Keystone: Kings' Rest (14)], [Keystone: The MOTHERLODDE!! (14)] , ...

This is useful for when we need to parse that from a discord bot or other websites.

**Comment by prg** [comment]
Some minor improvements:

- new configuration option for "report target":
![Anmerkung 2020-06-23 232032](https://user-images.githubusercontent.com/101409/85464679-38c83700-b5a8-11ea-809d-d668802f7e26.png)
`Guild` and `Party` should be fairly self-explanatory

- confirmation prompts for chat reports:
![Anmerkung 2020-06-23 232033](https://user-images.githubusercontent.com/101409/85465015-965c8380-b5a8-11ea-9629-9b73ff33b4f5.png)

- export functionality:
![Anmerkung 2020-06-23 232442](https://user-images.githubusercontent.com/101409/85465294-e9ced180-b5a8-11ea-9386-de4a594ff89b.png)

There are still ways to go in improving this, which is why I'd really like some feedback from maintainers here before I open a pull request in your faces.

**Comment by Stanzilla** [comment]
I like the idea, would love to define a feature list first though, which exactly did you have in mine in addition what you already mentioned? (Actually would love to get a complete list just for easier discussion)

**Comment by prg** [comment]
Let me say this first: reporting to party is basically everything I need, and I only built export because @dpyy requested it initially.

I can see some ways to improve on that small feature set, though:
- more chat report targets like `/w` or community channels (basically allow every possible arg combination of `SendChatMessage()`)
  - maybe except `/yell`
  - this requires an additional text input for targets like whisper or community channels, so keeping the UI in config is maybe not the best place
  - confirmation prompts should be enabled for all of these to prevent (accidental) spamming
- more control over output format
  - filter out realm names
  - omit character names completely, just output flat list of keys?
  - sorting by character name, keystone level, SavedInstances sort order, etc

Off the top of my head, that's all I can think of right now. Maybe someone else has different needs or ideas for related features.

**Comment by prg** [comment]
So I did some more touch-ups:

- if `db.Tooltip.ShowServer` is unchecked, server names will be filtered out as they would be in other places:
![Anmerkung 2020-07-16 182155](https://user-images.githubusercontent.com/101409/87697569-86dcee80-c792-11ea-9227-ca83b4e527ce.png)

- added a hover tooltip similar to others to show the current report target:
![Anmerkung 2020-07-16 182511](https://user-images.githubusercontent.com/101409/87697608-92c8b080-c792-11ea-9ba9-4fc4b5cc584f.png)

- some code reorganization

Even if we don't add any additional features/improvements, there's still work to be done (e.g. i18n). Nonetheless, I would like to get this merged, should I just open a pull request?

**Comment by Stanzilla** [comment]
Yes please!

**Comment by gigecogary** [comment]
Hi, is this feature merged? Can now I export my keys in the latest version of this addon?

**Comment by dpyy** [comment]
Hi, is this feature merged? Can now I export my keys in the latest version of this addon?

**Comment by LiangYuxuan** [comment]
Yes, but you need to use alpha since it's not released yet.

**Comment by gaveer** [comment]
but how you active the export ? click on what , do what .

**Comment by LiangYuxuan** [comment]
Click "Mythic Keystone" in the main tooltip

**Comment by dpyy** [comment]
When will this be released to production?

**Comment by Stanzilla** [comment]
Now :)
