### ISSUE TITLE
Tracking Rares that you can loot once per day

### ISSUE THREAD

**Issue by dwinfield** [SavedInstances/SavedInstances#406]
This expansion I was trying to kill a lot of the rares in Nazjatar/Mechagon/Vale/Uldum.  It would be amazing to be able to add an npc id and then be able to track which characters have killed them every day.

So if I could add IDs for Soundless/Rustfeather/Ha Li/Whatever I could easily see which characters have farmed those mobs instead of having to log into each character and run some macro to see if it's been done.

Most macros go off of a quest ID instead of an NPC ID so that could be how you track it.  For example this is how I track soundless and rustfeather

`/run for k,v in pairs({Rustfeather=55811,Soundless=56298}) do print(format("%s: %s", k, IsQuestFlaggedCompleted(v) and "\124cFFFF0000Dead\124r" or "\124cFF00FF00Alive\124r")) end
`

**Comment by Stanzilla** [comment]
We decided to not do rare tracking in SI

**Comment by raysmith59** [comment]
Just adding a +1 to this, I actually came close to adding Rustfeather to it successfully on my own when I was farming it on 15 toons per day but never quite got it working - it showed up on the list but only occasionally captured and showed that it had been killed, maybe because it's daily instead of weekly.  The request isn't to add all possible rares in, it's just to provide the ability for us to add our own IDs somewhere so we can choose which rares we want tracked, is usually won't be all that many.  Maybe just a new tab for rares that's free-form text that we can add IDs in one per line, doesn't have to be fancy.  This add-on does about 95% of what I'm looking for, rare tracking for mounts or tmogs would be the last 5%.

Please?  :)
