### ISSUE TITLE
Certain chars don't get saved to lfr

### ISSUE THREAD

**Issue by darkminaz** [SavedInstances/SavedInstances#426]
**Describe the bug**
I expected all my charakters to get saved and shown

**Screenshots**
https://i.imgur.com/uMFV3uB.png

**Did you try having SavedInstances as the only enabled addon and everything else (especially something like ElvUI) disabled?**

**Which version of SavedInstances are you using?**
9.0.2 - curseforge 

**Was it working in a previous version? If yes, which was the last good one?**
- works for my priest that i did it earlier in the week before i updated so 9.0.1 probably

**Comment by KatJon** [comment]
I also encountered this issue, even before updating to 9.0.1. This might be caused by some error on blizzard side, as for me, the LFR lockout is not displayed in the in-game calendar, despite being shown in Raid Lockouts tab

![WoWScrnShot_111220_085249](https://user-images.githubusercontent.com/10155820/98911277-a11aa500-24c4-11eb-8a27-71d8cb2487e1.jpg)
![WoWScrnShot_111220_085240](https://user-images.githubusercontent.com/10155820/98911279-a1b33b80-24c4-11eb-89de-178364a52f38.jpg)

**Comment by rodalpho** [comment]
Same issue here, lockouts show in raidinfo but not on calendar or in SavedInstances.

**Comment by bchevreau** [comment]
Hi, LFR lockouts have stopped working for me as well on all my characters. They actually show in raidinfo AND on the calendar, but not in savedinstances sheet, even when I force a particular LFR raid to "always show", nothing appears under the corresponding character.

Could it be because of the number of characters being too high? I am playing from an external SSD but I doubt this would have any issue on that type of data.

<img width="1440" alt="Screen Shot 2020-11-19 at 10 31 39 PM" src="https://user-images.githubusercontent.com/12772470/99726834-59dd7700-2ab7-11eb-8ecc-61bd1ed3fd1b.png">

**Comment by LiangYuxuan** [comment]
Caused by same reason in #547, check out #578 for more info.
