### ISSUE TITLE
Radiant Echoes Bosses

### ISSUE THREAD

**Issue by pax0707** [SavedInstances/SavedInstances#855]
**Is your feature request related to a problem? Please describe.**
When you check what event is up there's no way to see what character is not locked for weekly, only the number of events done.

**Describe the solution you'd like**
List each boss and/or zone separately.

**Comment by Spennig** [comment]
This would be lovely to have. I can't always recall which ones I did on which alt.

**Comment by LiangYuxuan** [comment]
May need some questID or example for this.

**Comment by Spennig** [comment]
QIDs are: 

78938 - Champion of the Waterlords
82676 - Broken Masquerade
82689 - Only Darkness

They are the daily Radiant Echoes quests (Account Wide shared) 

It would just be nice to know which are completed for the day, since my gameplay times are erratic and I alt a lot. Currently it shows on every alt the # completed of 3. It doesn't specify which ones, however.

Ideally, could it be made a shared save & specify which quests are complete? 

![image](https://github.com/user-attachments/assets/0306008c-e931-478b-883b-bf4bd08ae3ff)

**Comment by LiangYuxuan** [comment]
It'll show detailed list when you hover on.

**Comment by fzarr** [comment]
There's another addition to this I'd like to request - the first week of each kill per character gives a special reward. I'm not sure of the questId unfortunately but the item you get is https://www.wowhead.com/item=226256/token-of-the-remembrancers
